// src/constants/auditActions.ts
/**
 * Audit action constants for tracking user activities
 * Used by auditLogService to record system events
 */

export const AuditActions = {
  // Document actions
  DOCUMENTS_LIST_VIEWED: 'DOCUMENTS_LIST_VIEWED',
  DOCUMENT_URL_CREATED: 'DOCUMENT_URL_CREATED',
  DOCUMENT_DOWNLOAD_URL_CREATED: 'DOCUMENT_DOWNLOAD_URL_CREATED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  
  // Tax Calendar actions
  TAX_CALENDAR_VIEWED: 'TAX_CALENDAR_VIEWED',
  TAX_CALENDAR_SUMMARY_VIEWED: 'TAX_CALENDAR_SUMMARY_VIEWED',
  TAX_CALENDAR_UPCOMING_VIEWED: 'TAX_CALENDAR_UPCOMING_VIEWED',
  TAX_CALENDAR_CREATED: 'TAX_CALENDAR_CREATED',
  TAX_CALENDAR_ENTRY_VIEWED: 'TAX_CALENDAR_ENTRY_VIEWED',
  TAX_CALENDAR_UPDATED: 'TAX_CALENDAR_UPDATED',
  TAX_CALENDAR_DELETED: 'TAX_CALENDAR_DELETED',
  
  // Admin actions
  CLIENT_CREATED: 'CLIENT_CREATED',
  USER_INVITED: 'USER_INVITED',
  COMPANY_UPSERTED: 'COMPANY_UPSERTED',
} as const;

export type AuditAction = typeof AuditActions[keyof typeof AuditActions];
