// src/constants/auditActions.ts
/**
 * Audit action constants for tracking user activities
 * Used by auditLogService to record system events
 */

export const AuditActions = {
  // Document actions
  DOCUMENTS_LIST_VIEWED: 'DOCUMENTS_LIST_VIEWED',
  DOCUMENT_URL_CREATED: 'DOCUMENT_URL_CREATED',
  DOCUMENT_DOWNLOAD_URL_CREATED: 'DOCUMENT_DOWNLOAD_URL_CREATED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_ARCHIVED: 'DOCUMENT_ARCHIVED',
  DOCUMENT_PURGED: 'DOCUMENT_PURGED',
  DOCUMENT_FOLDER_CHANGED: 'DOCUMENT_FOLDER_CHANGED',
  DOCUMENT_TAGS_CHANGED: 'DOCUMENT_TAGS_CHANGED',
  DOCUMENT_PREVIEW_JOB_ENQUEUED: 'DOCUMENT_PREVIEW_JOB_ENQUEUED',
  DOCUMENT_PREVIEW_READY: 'DOCUMENT_PREVIEW_READY',
  DOCUMENT_PREVIEW_FAILED: 'DOCUMENT_PREVIEW_FAILED',
  DOCUMENT_PREVIEW_URL_CREATED: 'DOCUMENT_PREVIEW_URL_CREATED',
  DOCUMENT_EXPORT_CREATED: 'DOCUMENT_EXPORT_CREATED',
  DOCUMENT_EXPORT_READY: 'DOCUMENT_EXPORT_READY',
  DOCUMENT_EXPORT_FAILED: 'DOCUMENT_EXPORT_FAILED',
  DOCUMENT_EXPORT_URL_CREATED: 'DOCUMENT_EXPORT_URL_CREATED',
  
  // Folder actions
  FOLDER_CREATED: 'FOLDER_CREATED',
  FOLDER_RENAMED: 'FOLDER_RENAMED',
  FOLDER_DELETED: 'FOLDER_DELETED',
  
  // Tag actions
  TAG_CREATED: 'TAG_CREATED',
  TAG_DELETED: 'TAG_DELETED',
  
  // Tax Calendar actions
  TAX_CALENDAR_VIEWED: 'TAX_CALENDAR_VIEWED',
  TAX_CALENDAR_SUMMARY_VIEWED: 'TAX_CALENDAR_SUMMARY_VIEWED',
  TAX_CALENDAR_UPCOMING_VIEWED: 'TAX_CALENDAR_UPCOMING_VIEWED',
  TAX_CALENDAR_CREATED: 'TAX_CALENDAR_CREATED',
  TAX_CALENDAR_ENTRY_VIEWED: 'TAX_CALENDAR_ENTRY_VIEWED',
  TAX_CALENDAR_UPDATED: 'TAX_CALENDAR_UPDATED',
  TAX_CALENDAR_DELETED: 'TAX_CALENDAR_DELETED',
  
  // Admin actions
  CLIENT_CREATED: 'CLIENT_CREATED',
  USER_INVITED: 'USER_INVITED',
  COMPANY_UPSERTED: 'COMPANY_UPSERTED',
  ADMIN_DOCUMENTS_LISTED: 'ADMIN_DOCUMENTS_LISTED',
  
  // External storage actions
  EXTERNAL_STORAGE_CONNECTED: 'EXTERNAL_STORAGE_CONNECTED',
  EXTERNAL_STORAGE_DISCONNECTED: 'EXTERNAL_STORAGE_DISCONNECTED',
  DOCUMENT_EXTERNAL_UPLOAD_ENQUEUED: 'DOCUMENT_EXTERNAL_UPLOAD_ENQUEUED',
  DOCUMENT_EXTERNAL_UPLOAD_SUCCEEDED: 'DOCUMENT_EXTERNAL_UPLOAD_SUCCEEDED',
  DOCUMENT_EXTERNAL_UPLOAD_FAILED: 'DOCUMENT_EXTERNAL_UPLOAD_FAILED',
  
  // Messaging actions
  CONVERSATION_CREATE: 'CONVERSATION_CREATE',
  MESSAGE_CREATE: 'MESSAGE_CREATE',
  EXPORT_MESSAGES: 'EXPORT_MESSAGES',
} as const;

export type AuditAction = typeof AuditActions[keyof typeof AuditActions];
