-- Bubble Password Reset Tokens Table
-- Created: 2025-01-06
-- Purpose: Store Bubble-generated reset tokens for mutual password reset verification flow

-- Create bubble_password_reset_tokens table
create table if not exists public.bubble_password_reset_tokens (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  reset_token text not null,
  expires_at timestamptz not null,
  used_at timestamptz null,
  created_at timestamptz not null default now()
);

-- Create indexes for faster lookups
create index if not exists bubble_password_reset_tokens_email_idx on public.bubble_password_reset_tokens(email);
create index if not exists bubble_password_reset_tokens_reset_token_idx on public.bubble_password_reset_tokens(reset_token);
create index if not exists bubble_password_reset_tokens_expires_at_idx on public.bubble_password_reset_tokens(expires_at);

-- Add comments for documentation
comment on table public.bubble_password_reset_tokens is 'Stores Bubble-generated password reset tokens for mutual verification flow';
comment on column public.bubble_password_reset_tokens.reset_token is 'Raw token generated by Bubble (not hashed, trusted after DB validation)';
comment on column public.bubble_password_reset_tokens.expires_at is 'Token expiry timestamp (default 30 minutes from creation)';
comment on column public.bubble_password_reset_tokens.used_at is 'Timestamp when token was used (null = not yet used)';

-- Enable Row Level Security
alter table public.bubble_password_reset_tokens enable row level security;

-- RLS Policy: Only service role can access (backend only, no direct user access)
create policy "bubble_password_reset_tokens_service_only"
on public.bubble_password_reset_tokens
for all
using (false)
with check (false);

-- Create cleanup function for expired/used tokens
create or replace function cleanup_bubble_password_reset_tokens()
returns void
language plpgsql
security definer
as $$
begin
  -- Delete tokens that are either used or expired for more than 24 hours
  delete from public.bubble_password_reset_tokens
  where (used_at is not null and used_at < now() - interval '24 hours')
     or (used_at is null and expires_at < now() - interval '24 hours');
end;
$$;

comment on function cleanup_bubble_password_reset_tokens is 'Removes old used/expired Bubble password reset tokens (can be called by cron job)';
